[project]
name = "railway-analytics-duckdb"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "dbt>=1.0.0.40.5",
    "dbt-core>=1.10.3",
    "dbt-duckdb>=1.9.4",
    "dbt-postgres>=1.9.0",
    "duckdb>=1.3.2",
    "sqlfluff>=3.4.1",
]
